global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  resolve_timeout: 1m

route:
  receiver: 'all-notifications'

receivers:
- name: 'all-notifications'
  slack_configs:
  - channel: '#anton-volchkov'
  email_configs:
  - to: ***@gmail.com
    from: ***@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: ***@gmail.com
    auth_identity: ***@gmail.com
    auth_password: password
    send_resolved: true
