global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#anton-volchkov'
