---
- name: Install docker
  hosts: all
  become: true
  gather_facts: no
  tags: ["install"]
  tasks:
    - name: Add repo key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add repo
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu  xenial stable"
        state: present

    - name: Install docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present

    - name: add ansible user to group
      user:
        name: gcp
        groups: docker
        append: yes
