{
 "title": "RedditApp Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "95 procentile request latency",
   "type": "graph",
   "description": "95 procentile",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "UI HTTP Requests rate",
   "type": "graph",
   "description": "All HTTP requests ot UI service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count[1m])" }
   ]
  },
  {
   "title": "Rate of HTTP request (error requests)",
   "type": "graph",
   "description": "Requests begining with 4 or 5",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  }
 ]
}