---
# tasks file for gitlab
- debug: msg="Start configuring GitLab"

- name: Create folders
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /srv/gitlab/config
    - /srv/gitlab/data
    - /srv/gitlab/logs

- name: Copy docker-compose.yml
  template:
    src: compose.yml.j2
    dest: /srv/gitlab/docker-compose.yml

- name: Start GitLab
  shell:
    cmd: docker-compose up -d
    chdir: /srv/gitlab
