plugin: gcp_compute
projects:
  - docker-283909
#zones: # populate inventory with instances in these regions
#  - europe-west1-b
hostnames:
  - name
groups:
  docker: inventory_hostname.startswith('docker-host')
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
filters: []
auth_kind: serviceaccount       # gcp authentication kind. with service account you should provide the service account json key file to authenticate
service_account_file: ./keys/docker-credentials.json
